### PR TITLE
Fix: Switch between legacy and new logstash format

### PR DESCRIPTION
**Pull request by andreas-marschke**
Use a flag `legacy` to tell bunyan-logstash to either use
legacy logstash message format with `@`-prefixed standard
fields or use newer non-prefixed formats.

### CODE REVIEW

**Comment by rooftopsparrow** [comment]
bump :+1:

**Comment by zowers** [comment]
it is better to bump to version 0.3.0 instead having 'legacy' option.
no new installs need the option, only old ones, which will be sticking to the ~0.2.0 as per semver rules.

so I would suggest to choose my PR https://github.com/sheknows/bunyan-logstash/pull/6 instead of this one.

**Comment by andreas-marschke** [comment]
@zowers Good point. Thanks!

I have to wonder though as there has been no or not a lot of feedback on this issue if it would be wise to let another contributor take over the project entirely. The current maintainer "sheknows" appears not to be too active anymore(last commit Dec 2013 no communication with the contributors/pull requests/issues).

I'd say it's up for grabs if anyone would want to take it.

**Comment by zowers** [comment]
We use our fork containing my modifications in dev and production for 3 weeks, no problems.
The only issue was migration to the new scheme - had to modify kibana dashboards to match the new data scheme.

**Comment by andreas-marschke** [comment]
Cool! 

Now how would you go about moving the official package to your version?

**Comment by luthermonson** [comment]
@andreas-marschke sorry, no one watches this repo that often. I'll take a look and leave comments and merge as needed.

**Comment by luthermonson** [comment]
@andreas-marschke I vote for 0.3.0, if no one else cares maybe I'll just merge some of the other stuff as that which will give you your new logstash fields. you tied to this legacy param idea?

**Comment by andreas-marschke** [comment]
Nope. Have fun!i

**Pull request closed without merging**
