### PR TITLE
Fix #4 Logstash fields don't use @ anymore

### LINKED ISSUE #4: Logstash fields don't use @ anymore
Only `@timestamp` still starts with @. https://gist.github.com/jordansissel/2996677

### PR DESCRIPTION
**Pull request by zowers**
fix https://github.com/sheknows/bunyan-logstash/issues/4
contains tests and "limit clone depth" by @liukun

### CODE REVIEW

**Comment by paulredmond** [comment]
@zowers would you or @liukun be interested in taking ownership of this repo? We don't have time to maintain it any longer.

**Comment by paulredmond** [comment]
Checked back and we are still using it on some projects so we may continue to maintain it. I'll let you know.

**Comment by zowers** [comment]
it's 1 simple 100 loc javascript file which does not need a lot of maintaining

**Comment by liukun** [comment]
I'm using https://github.com/chris-rock/bunyan-logstash-tcp now.

**Comment by EgoAleSum** [comment]
@zowers  is there a reason why there's still the `@` with `@timestamp`?

@paulredmond so... can you merge this? :)

**Comment by zowers** [comment]
sure, timestamp and version are the only fields which must have @ in the new schema

**Comment by zowers** [comment]
https://gist.github.com/jordansissel/2996677

**Comment by EgoAleSum** [comment]
Thanks for the explanation!

**Comment by FrankZZ** [comment]
@paulredmond  I'm waiting for this to be merged, any updates on this?

**Comment by paulredmond** [comment]
I am working with the NPM package owner to allow me to become an owner and publish the release version to NPM.

**Comment by paulredmond** [comment]
NPM module is published with this PR.

```
npm install bunyan-logstash@0.3.1
```

**Pull request merged**
